apiVersion: apps/v1
kind: Deployment
metadata:
  name: kping-deployment
  labels:
    app: kping-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kping-server
  template:
    metadata:
      labels:
        app: kping-server
    spec:
      containers:
      - name: kping-server
        image: kayrosuno/kping:latest
        ports:
        - containerPort: 25450
          protocol: TCP
          name: "tcp"
        - containerPort: 25450
          protocol: UDP
          name: "quic-udp"
        - containerPort: 25451
          protocol: UDP
          name: "udp"
        volumeMounts:
          - name: data1
            mountPath: /app/data1
          - name: data2
            mountPath: /app/tmp
          - name: data3
            mountPath: /app/ds415
      volumes:
        - name: data1
          persistentVolumeClaim:
            claimName: local-pvc
        - name: data2
          hostPath:
            path: /tmp
            type: DirectoryOrCreate
        - name: data3
          persistentVolumeClaim:
            claimName: pvc-smb-5g