apiVersion: v1
kind: Pod
metadata:
  name: kping-pod1
  annotations:
        k8s.v1.cni.cncf.io/networks: '[
            { 
              "name": "data-n2-nad" 
            }
          ]'
  labels:
    app.kubernetes.io/name: myapp
  namespace: italtel
spec:
  containers:
  - name: myapp
    image: kayrosuno/kping:0.3.2
    requests: 
      intel.com/pci_sriov_net_data_n2: '1'
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 25450

