apiVersion: k8s.cni.cncf.io/v1
kind: NetworkAttachmentDefinition
metadata:
  annotations:
    k8s.v1.cni.cncf.io/resourceName: intel.com/pci_sriov_net_data_n2
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"k8s.cni.cncf.io/v1","kind":"NetworkAttachmentDefinition","metadata":{"annotations":{"k8s.v1.cni.cncf.io/resourceName":"intel.com/pci_sriov_net_data_n6"},"name":"data-n2-nad","namespace":"italtel"},"spec":{"config":"{\n  \"cniVersion\": \"0.3.1\",\n  \"type\": \"sriov\",\n  \"ipam\": {\n    \"type\": \"host-local\",\n    \"subnet\": \"192.168.30.0/24\",\n    \"rangeStart\": \"192.168.30.10\",\n    \"rangeEnd\": \"192.168.30.200\",\n    \"gateway\": \"192.168.30.1\"\n  }\n}\n"}}
  creationTimestamp: 2025-10-27T13:30:02Z
  generation: 2
  name: data-n2-nad
  namespace: italtel
  resourceVersion: "2781097"
  uid: 98803b8b-492e-4e30-955b-8187cff6e65b
spec:
  config: |
    {
      "cniVersion": "0.3.1",
      "type": "sriov",
      "ipam": {
        "type": "host-local",
        "subnet": "192.168.30.0/24",
        "rangeStart": "192.168.30.10",
        "rangeEnd": "192.168.30.200",
        "gateway": "192.168.30.1"
      }
    }
