apiVersion: apps/v1
kind: Deployment
metadata:
  name: qping-deployment
  labels:
    app: qping
spec:
  replicas: 2
  selector:
    matchLabels:
      app: qping
  template:
    metadata:
      labels:
        app: qping
    spec:
      containers:
      - name: qping
        image: kayrosuno/qping-arm64:0.3.2
        ports:
        - containerPort: 25450
