apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  creationTimestamp: null
  name: ubuntu
spec:
  runStrategy: Always
  template:
    metadata:
      creationTimestamp: null
    spec:
      domain:
        devices:
          disks:
            - disk:
                bus: virtio
              name: containerdisk
            - disk:
                bus: virtio
              name: cloudinitdisk
          rng: {}
        resources:
          requests:
            memory: 1Gi
      terminationGracePeriodSeconds: 180
      volumes:
        - containerDisk:
            image: quay.io/containerdisks/ubuntu:24.04
          name: containerdisk
        - cloudInitNoCloud:
            userData: |-
              #cloud-config
              password: ubuntu
              chpasswd: { expire: False }
              # Disable SELinux for now, so qemu-guest-agent can write the authorized_keys file
              # The selinux-policy is too restrictive currently, see open bugs:
              #   - https://bugzilla.redhat.com/show_bug.cgi?id=1917024
              #   - https://bugzilla.redhat.com/show_bug.cgi?id=2028762
              #   - https://bugzilla.redhat.com/show_bug.cgi?id=2057310
              bootcmd:
                - setenforce 0
          name: cloudinitdisk
status: {}