# syntax=docker/dockerfile:1



# Build the application from source
FROM golang:1.26.5 AS build-stage

WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download

COPY *.go ./

RUN CGO_ENABLED=0 GOOS=linux go build -o /app/kping

# Run the tests in the container
#FROM build-stage AS run-test-stage
#RUN go test -v ./...

# Deploy the application binary into a clean image
FROM alpine:3.23.5 AS build-release-stage

ARG USERNAME=iacobus
ARG USER_UID=2000
ARG USER_GID=$USER_UID

#Instalar net-tools
RUN apk update && apk add --no-cache curl net-tools iproute2 iputils sudo \
    && addgroup -g $USER_GID $USERNAME \
    && adduser -D -u $USER_UID -G $USERNAME -h /home/$USERNAME $USERNAME

#RUN echo $USERNAME ALL=\(root\) NOPASSWD:ALL > /etc/sudoers.d/$USERNAME \
#    && chmod 0440 /etc/sudoers.d/$USERNAME 

# ********************************************************
# * Anything else you want to do like clean up goes here *
# ********************************************************

# [Optional] Set the default user. Omit if you want to keep the default as root.
USER $USERNAME


# Label docker image
LABEL version="0.3.2"
LABEL maintaner="Alejandro Garcia"
LABEL release-date="04-07-2025"
#LABEL promoted="true"



WORKDIR /app

COPY --from=build-stage /app/kping /app/kping

EXPOSE 25450/udp
EXPOSE 25450/tcp

#Ejecuta kping en modo server, default port 25450 UDP (QUIC)
ENTRYPOINT ["/app/kping","server"]
